# Site settings
title:        "Journalism Entries"
description:  "Home for my Journalism I projects"
baseurl:      "" # the subpath of your site, e.g. /blog/
url:          "http://hsquillin.github.io"
permalink:    /:year/:title
github:       "HSQuillin"
email:        "mail@example.com"
disqus-id:    "example" #leave blank if you dont want comments.

# Build settings
markdown:     kramdown
sass:
    style: :compressed